# Generated by Django 4.1.3 on 2022-12-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='Customer',
        ),
    ]
