# Generated by Django 4.1.3 on 2022-12-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customer_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_phone', models.BigIntegerField()),
                ('seller_address', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=20)),
                ('acc_holder', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('acc_number', models.CharField(max_length=20)),
                ('seller_username', models.CharField(max_length=20)),
                ('seller_password', models.CharField(max_length=20)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
        ),
    ]
