# Generated by Django 4.1.3 on 2022-12-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_seller_acc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
