# Generated by Django 4.1.3 on 2022-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_customer_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_email',
            field=models.CharField(max_length=50),
        ),
    ]
