# Generated by Django 4.1.1 on 2022-12-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_customer_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_gender',
            new_name='customer_gender',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_number',
            new_name='customer_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_password',
            new_name='customer_password',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default='', upload_to='customer/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='acc_number',
            field=models.BigIntegerField(default=''),
        ),
    ]
